const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const dbPath = path.resolve(__dirname, '../database.json');
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

const now = Date.now();

// Consents for all enterprise employees
const enterpriseConsents = [
  { email: 'jordan.hayes@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - DevOps' },
  { email: 'claire.dupont@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - Support' },
  { email: 'tariq.mansoor@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - AI Research' },
  { email: 'kavita.sharma@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - Product' },
  { email: 'vikram.patel@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - AppSec QA' },
  { email: 'finance@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - Finance' },
  { email: 'marketing@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - Marketing' },
  { email: 'legal@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - Legal' },
  { email: 'hr@nexus-corp.com', userAgent: 'AEGIS Enterprise Portal - People Ops' }
];

db.consents = db.consents || [];
for (const ec of enterpriseConsents) {
  if (!db.consents.some(c => c.email === ec.email)) {
    db.consents.push({
      email: ec.email,
      granted: true,
      timestamp: new Date(now - 86400000 * 5).toISOString(),
      version: 'v1.0-GDPR-DPDP',
      ipAddress: '10.0.12.44',
      userAgent: ec.userAgent
    });
  }
}

// Enterprise Employee Interaction Logs
const newEmployeeLogs = [
  // =========================================================================
  // 1. JORDAN HAYES (Cloud DevOps & SRE) - Repeated Credential Violations
  // Blind Spot: CREDENTIAL | Score: ~44 (HIGH RISK) | Needs SEC-101
  // =========================================================================
  {
    id: `aegis-evt-jordan-01`,
    timestamp: new Date(now - 7200000 * 6).toISOString(),
    user: 'jordan.hayes@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Generate Terraform module for AWS VPC with private subnets').digest('hex'),
    original_prompt: 'Generate Terraform module for AWS VPC with private subnets across 3 AZs',
    sanitized_prompt: 'Generate Terraform module for AWS VPC with private subnets across 3 AZs',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Generate Terraform module for AWS VPC with private subnets across 3 AZs',
    suggested_safe_prompt: 'Prompt verified and approved for transmission.',
    business_impact: 'Safe compliant infrastructure query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 19,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-jordan-02`,
    timestamp: new Date(now - 7200000 * 5).toISOString(),
    user: 'jordan.hayes@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('AWS provider credentials debug').digest('hex'),
    original_prompt: '[REDACTED_BLOCKED_CONTENT]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 98,
    risk_level: 'CRITICAL',
    attack_type: 'CREDENTIAL',
    reasons: ['Detected explicit third-party API key, access token, or incoming webhook.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked by security policy: Strict prohibition against forwarding cryptographic keys or cloud provider secrets.',
    business_impact: 'Critical perimeter block: Cloud provider access keys intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Block Credentials & Private Keys: Strict prohibition against forwarding cryptographic keys, credentials, or connection strings to external AI models.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-jordan-03`,
    timestamp: new Date(now - 7200000 * 4).toISOString(),
    user: 'jordan.hayes@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('PostgreSQL connection debug').digest('hex'),
    original_prompt: '[REDACTED_BLOCKED_CONTENT]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 95,
    risk_level: 'CRITICAL',
    attack_type: 'CREDENTIAL',
    reasons: ['Detected database connection string containing embedded cleartext credentials.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Production database connection strings must not be forwarded to external AI models.',
    business_impact: 'High-risk perimeter stop: Database credentials intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Database Connection Strings & Secrets.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-jordan-04`,
    timestamp: new Date(now - 7200000 * 3).toISOString(),
    user: 'jordan.hayes@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Private certificate key validation').digest('hex'),
    original_prompt: '[REDACTED_BLOCKED_CONTENT]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 99,
    risk_level: 'CRITICAL',
    attack_type: 'CREDENTIAL',
    reasons: ['Detected cryptographic private key payload.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Cryptographic private keys must never be transmitted outside the enterprise boundary.',
    business_impact: 'Critical perimeter stop: Cryptographic private key intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Block Credentials & Private Keys.',
    provider_id: 'provider-safe-mock',
    latency_ms: 3,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-jordan-05`,
    timestamp: new Date(now - 7200000 * 2).toISOString(),
    user: 'jordan.hayes@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('GitLab CI deployment webhook token').digest('hex'),
    original_prompt: '[REDACTED_BLOCKED_CONTENT]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 92,
    risk_level: 'CRITICAL',
    attack_type: 'CREDENTIAL',
    reasons: ['Detected explicit third-party API key, access token, or incoming webhook.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Third-party deployment tokens must be managed using vault secrets.',
    business_impact: 'Critical perimeter block: Deployment webhook token intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Block Credentials & Private Keys.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-jordan-06`,
    timestamp: new Date(now - 3600000).toISOString(),
    user: 'jordan.hayes@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Kubernetes PodDisruptionBudgets autoscaling').digest('hex'),
    original_prompt: 'How do Kubernetes PodDisruptionBudgets interact with node drain during cluster autoscaling?',
    sanitized_prompt: 'How do Kubernetes PodDisruptionBudgets interact with node drain during cluster autoscaling?',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'How do Kubernetes PodDisruptionBudgets interact with node drain during cluster autoscaling?',
    suggested_safe_prompt: 'Prompt verified and approved for transmission.',
    business_impact: 'Safe compliant infrastructure query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 21,
    has_file: false,
    override_status: 'NONE'
  },

  // =========================================================================
  // 2. CLAIRE DUPONT (Customer Support) - Recurring PII & Data Privacy Leaks
  // Blind Spot: PII | Score: ~58 (NEEDS COACHING) | Needs PRIV-201
  // =========================================================================
  {
    id: `aegis-evt-claire-01`,
    timestamp: new Date(now - 86400000).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Draft polite apology for delivery delay').digest('hex'),
    original_prompt: 'Draft a polite and empathetic email apologizing to a customer for a shipment delay due to severe winter weather.',
    sanitized_prompt: 'Draft a polite and empathetic email apologizing to a customer for a shipment delay due to severe winter weather.',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Draft a polite and empathetic email apologizing to a customer for a shipment delay due to severe winter weather.',
    suggested_safe_prompt: 'Prompt verified and approved for transmission.',
    business_impact: 'Safe compliant customer support draft.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 17,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-claire-02`,
    timestamp: new Date(now - 7200000 * 8).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Customer ticket with SSN and phone').digest('hex'),
    original_prompt: 'Draft response for ticket #5821: Client Marcus Vance (SSN [REDACTED_SSN], cell [REDACTED_PHONE]) is disputing an overcharge of $240.',
    sanitized_prompt: 'Draft response for ticket #5821: Client Marcus Vance (SSN [REDACTED_SSN], cell [REDACTED_PHONE]) is disputing an overcharge of $240.',
    risk_score: 65,
    risk_level: 'MEDIUM',
    attack_type: 'PII',
    reasons: ['Detected Social Security Number (SSN).', 'Detected telephone contact number.'],
    action: 'MODIFIED',
    rewritten_prompt: 'Draft response for ticket #5821: Client Marcus Vance (SSN [REDACTED_SSN], cell [REDACTED_PHONE]) is disputing an overcharge of $240.',
    suggested_safe_prompt: 'Customer PII redacted before external AI processing.',
    business_impact: 'Privacy compliance requirement: PII masked before external forwarding.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'PII masked in accordance with GDPR / DPDP.',
    provider_id: 'provider-safe-mock',
    latency_ms: 22,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-claire-03`,
    timestamp: new Date(now - 7200000 * 6).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Customer email address in prompt').digest('hex'),
    original_prompt: 'Help reply to corporate account manager at [REDACTED_EMAIL] regarding their pending subscription renewal.',
    sanitized_prompt: 'Help reply to corporate account manager at [REDACTED_EMAIL] regarding their pending subscription renewal.',
    risk_score: 40,
    risk_level: 'MEDIUM',
    attack_type: 'PII',
    reasons: ['Detected personal or corporate email address.'],
    action: 'MODIFIED',
    rewritten_prompt: 'Help reply to corporate account manager at [REDACTED_EMAIL] regarding their pending subscription renewal.',
    suggested_safe_prompt: 'Email address redacted before forwarding.',
    business_impact: 'Privacy compliance requirement: Email masked before external forwarding.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'PII masked in accordance with GDPR / DPDP.',
    provider_id: 'provider-safe-mock',
    latency_ms: 18,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-claire-04`,
    timestamp: new Date(now - 7200000 * 4).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Credit card dispute ticket').digest('hex'),
    original_prompt: 'Refund verification for ticket #9034: Client card ending in [REDACTED_CREDIT_CARD] was charged twice during checkout.',
    sanitized_prompt: 'Refund verification for ticket #9034: Client card ending in [REDACTED_CREDIT_CARD] was charged twice during checkout.',
    risk_score: 75,
    risk_level: 'HIGH',
    attack_type: 'PII',
    reasons: ['Detected payment card number (PCI-DSS).'],
    action: 'MODIFIED',
    rewritten_prompt: 'Refund verification for ticket #9034: Client card ending in [REDACTED_CREDIT_CARD] was charged twice during checkout.',
    suggested_safe_prompt: 'Payment card data masked before external forwarding.',
    business_impact: 'PCI-DSS / Privacy requirement: Payment card numbers masked.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Payment card data masked in accordance with PCI-DSS / Privacy Policy.',
    provider_id: 'provider-safe-mock',
    latency_ms: 25,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-claire-05`,
    timestamp: new Date(now - 7200000 * 2).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Customer contact details in chat').digest('hex'),
    original_prompt: 'Compose an escalation summary for user David Miller ([REDACTED_EMAIL], +1 [REDACTED_PHONE]) experiencing billing lockout.',
    sanitized_prompt: 'Compose an escalation summary for user David Miller ([REDACTED_EMAIL], +1 [REDACTED_PHONE]) experiencing billing lockout.',
    risk_score: 55,
    risk_level: 'MEDIUM',
    attack_type: 'PII',
    reasons: ['Detected personal or corporate email address.', 'Detected telephone contact number.'],
    action: 'MODIFIED',
    rewritten_prompt: 'Compose an escalation summary for user David Miller ([REDACTED_EMAIL], +1 [REDACTED_PHONE]) experiencing billing lockout.',
    suggested_safe_prompt: 'Customer contact details redacted.',
    business_impact: 'Privacy compliance requirement: PII masked before external forwarding.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'PII masked in accordance with GDPR / DPDP.',
    provider_id: 'provider-safe-mock',
    latency_ms: 20,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-claire-06`,
    timestamp: new Date(now - 3600000 * 2).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Bulk SSN parse attempt').digest('hex'),
    original_prompt: '[REDACTED_BLOCKED_CONTENT]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 94,
    risk_level: 'CRITICAL',
    attack_type: 'PII',
    reasons: ['Detected unredacted Social Security Numbers (SSN) in bulk context.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Bulk client PII transmission prohibited by Data Loss Prevention boundary.',
    business_impact: 'Critical privacy violation blocked.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Block SSN / National Identifiers.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-claire-07`,
    timestamp: new Date(now - 1800000).toISOString(),
    user: 'claire.dupont@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Conflict de-escalation tips').digest('hex'),
    original_prompt: 'What are effective conflict de-escalation phrases to use in chat support without making false promises?',
    sanitized_prompt: 'What are effective conflict de-escalation phrases to use in chat support without making false promises?',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'What are effective conflict de-escalation phrases to use in chat support without making false promises?',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant customer support query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 19,
    has_file: false,
    override_status: 'NONE'
  },

  // =========================================================================
  // 3. TARIQ AL-MANSOOR (Applied AI Research) - Adversarial Prompt Injections
  // Blind Spot: PROMPT_INJECTION | Score: ~44 (HIGH RISK) | Needs AUP-401
  // =========================================================================
  {
    id: `aegis-evt-tariq-01`,
    timestamp: new Date(now - 86400000 * 2).toISOString(),
    user: 'tariq.mansoor@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Multi-query attention explanation').digest('hex'),
    original_prompt: 'Explain how multi-query attention (MQA) reduces key-value cache memory compared to standard multi-head attention.',
    sanitized_prompt: 'Explain how multi-query attention (MQA) reduces key-value cache memory compared to standard multi-head attention.',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Explain how multi-query attention (MQA) reduces key-value cache memory compared to standard multi-head attention.',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant AI research query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 22,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-tariq-02`,
    timestamp: new Date(now - 7200000 * 6).toISOString(),
    user: 'tariq.mansoor@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('DAN jailbreak test').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 96,
    risk_level: 'CRITICAL',
    attack_type: 'PROMPT_INJECTION',
    reasons: ['Detected adversarial prompt override or jailbreak styling.', 'Detected attempt to extract system prompt / boundary configuration.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Prompt Injection & Adversarial Jailbreak Guardrail.',
    business_impact: 'Adversarial bypass prevention: Jailbreak instruction intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Prompt Injection & Adversarial Jailbreak Guardrail.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-tariq-03`,
    timestamp: new Date(now - 7200000 * 4).toISOString(),
    user: 'tariq.mansoor@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Persona spoofing bypass').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 92,
    risk_level: 'CRITICAL',
    attack_type: 'PROMPT_INJECTION',
    reasons: ['Detected persona spoofing and behavioral bypass instruction.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Boundary Guardrail Violation.',
    business_impact: 'Perimeter block: Jailbreak persona spoofing detected.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Boundary Guardrail Violation.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-tariq-04`,
    timestamp: new Date(now - 7200000 * 2).toISOString(),
    user: 'tariq.mansoor@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Delimiter evasion attempt').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 98,
    risk_level: 'CRITICAL',
    attack_type: 'PROMPT_INJECTION',
    reasons: ['Detected delimiter boundary evasion and system prompt exfiltration payload.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Delimiter escape and system prompt exfiltration detected.',
    business_impact: 'Critical boundary block: Delimiter escape detected.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Prompt Injection & Boundary Guardrail.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-tariq-05`,
    timestamp: new Date(now - 3600000 * 3).toISOString(),
    user: 'tariq.mansoor@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Directive override test').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 97,
    risk_level: 'CRITICAL',
    attack_type: 'PROMPT_INJECTION',
    reasons: ['Detected adversarial directive override and safety boundary disablement.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked by security policy: Strict prohibition against prompt injection.',
    business_impact: 'Critical security boundary block: Directive override intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Prompt Injection Guardrail.',
    provider_id: 'provider-safe-mock',
    latency_ms: 3,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-tariq-06`,
    timestamp: new Date(now - 1800000).toISOString(),
    user: 'tariq.mansoor@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('RAG hallucination evaluation techniques').digest('hex'),
    original_prompt: 'What are the latest techniques for evaluating hallucinations in retrieval-augmented generation (RAG) pipelines?',
    sanitized_prompt: 'What are the latest techniques for evaluating hallucinations in retrieval-augmented generation (RAG) pipelines?',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'What are the latest techniques for evaluating hallucinations in retrieval-augmented generation (RAG) pipelines?',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant AI research query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 24,
    has_file: false,
    override_status: 'NONE'
  },

  // =========================================================================
  // 4. KAVITA SHARMA (Product Architecture) - Confidential Project Codenames
  // Blind Spot: CONFIDENTIAL_TECHNICAL | Score: ~72 (NEEDS COACHING) | Needs IP-501
  // =========================================================================
  {
    id: `aegis-evt-kavita-01`,
    timestamp: new Date(now - 86400000).toISOString(),
    user: 'kavita.sharma@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Event-driven microservices architecture').digest('hex'),
    original_prompt: 'Outline the key architectural components of an event-driven microservices architecture using Apache Kafka.',
    sanitized_prompt: 'Outline the key architectural components of an event-driven microservices architecture using Apache Kafka.',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Outline the key architectural components of an event-driven microservices architecture using Apache Kafka.',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant product architecture query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 20,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-kavita-02`,
    timestamp: new Date(now - 7200000 * 5).toISOString(),
    user: 'kavita.sharma@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Orion-Core roadmap draft').digest('hex'),
    original_prompt: 'Draft the Q4 product roadmap presentation focusing on [REDACTED_PROJECT_CODENAME] architecture and customer onboarding timeline.',
    sanitized_prompt: 'Draft the Q4 product roadmap presentation focusing on [REDACTED_PROJECT_CODENAME] architecture and customer onboarding timeline.',
    risk_score: 40,
    risk_level: 'MEDIUM',
    attack_type: 'CONFIDENTIAL_TECHNICAL',
    reasons: ['Matched confidential enterprise keyword: Orion-Core.'],
    action: 'MODIFIED',
    rewritten_prompt: 'Draft the Q4 product roadmap presentation focusing on [REDACTED_PROJECT_CODENAME] architecture and customer onboarding timeline.',
    suggested_safe_prompt: 'Confidential project codename redacted before external forwarding.',
    business_impact: 'Trade secret protection: Internal project codename redacted before provider transit.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Codename redacted in accordance with IP Protection Policy.',
    provider_id: 'provider-safe-mock',
    latency_ms: 18,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-kavita-03`,
    timestamp: new Date(now - 7200000 * 3).toISOString(),
    user: 'kavita.sharma@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Internal hostname leakage').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 85,
    risk_level: 'HIGH',
    attack_type: 'CONFIDENTIAL_TECHNICAL',
    reasons: ['Prevents leakage of internal infrastructure hostnames.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Internal infrastructure hostnames must not be transmitted.',
    business_impact: 'Infrastructure security: Internal hostnames blocked from transit.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Internal Infrastructure Protection.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-kavita-04`,
    timestamp: new Date(now - 7200000).toISOString(),
    user: 'kavita.sharma@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Technical dependencies of Orion-Core').digest('hex'),
    original_prompt: 'Summarize the technical dependencies between [REDACTED_PROJECT_CODENAME] and our legacy billing engine.',
    sanitized_prompt: 'Summarize the technical dependencies between [REDACTED_PROJECT_CODENAME] and our legacy billing engine.',
    risk_score: 40,
    risk_level: 'MEDIUM',
    attack_type: 'CONFIDENTIAL_TECHNICAL',
    reasons: ['Matched confidential enterprise keyword: Orion-Core.'],
    action: 'MODIFIED',
    rewritten_prompt: 'Summarize the technical dependencies between [REDACTED_PROJECT_CODENAME] and our legacy billing engine.',
    suggested_safe_prompt: 'Confidential project codename redacted.',
    business_impact: 'Trade secret protection: Internal project codename redacted before provider transit.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Codename redacted in accordance with IP Protection Policy.',
    provider_id: 'provider-safe-mock',
    latency_ms: 19,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-kavita-05`,
    timestamp: new Date(now - 1200000).toISOString(),
    user: 'kavita.sharma@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('SLA benchmarks').digest('hex'),
    original_prompt: 'What are standard industry SLA definitions for enterprise SaaS 99.9% vs 99.99% availability?',
    sanitized_prompt: 'What are standard industry SLA definitions for enterprise SaaS 99.9% vs 99.99% availability?',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'What are standard industry SLA definitions for enterprise SaaS 99.9% vs 99.99% availability?',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant product query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 23,
    has_file: false,
    override_status: 'NONE'
  },

  // =========================================================================
  // 5. VIKRAM PATEL (AppSec QA) - Live SQL Injection & Exploit Strings
  // Blind Spot: APPSEC_EXPLOIT | Score: ~58 (NEEDS COACHING) | Needs APPSEC-301
  // =========================================================================
  {
    id: `aegis-evt-vikram-01`,
    timestamp: new Date(now - 86400000).toISOString(),
    user: 'vikram.patel@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('SAST vs DAST differences').digest('hex'),
    original_prompt: 'Explain the differences between static application security testing (SAST) and dynamic analysis (DAST) in a CI/CD pipeline.',
    sanitized_prompt: 'Explain the differences between static application security testing (SAST) and dynamic analysis (DAST) in a CI/CD pipeline.',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Explain the differences between static application security testing (SAST) and dynamic analysis (DAST) in a CI/CD pipeline.',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant application security query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 18,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-vikram-02`,
    timestamp: new Date(now - 7200000 * 5).toISOString(),
    user: 'vikram.patel@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('SQL injection test string').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 92,
    risk_level: 'CRITICAL',
    attack_type: 'APPSEC_EXPLOIT',
    reasons: ['Detected live SQL injection exploit signature.', 'Detected UNION SELECT database exfiltration payload.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Active SQL injection exploit payloads cannot be forwarded to external AI providers.',
    business_impact: 'AppSec perimeter block: Active SQL injection payload intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: AppSec Exploit & Injection Guardrail.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-vikram-03`,
    timestamp: new Date(now - 7200000 * 3).toISOString(),
    user: 'vikram.patel@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('XSS document.cookie payload').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 94,
    risk_level: 'CRITICAL',
    attack_type: 'APPSEC_EXPLOIT',
    reasons: ['Detected cross-site scripting (XSS) payload with document.cookie exfiltration.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: Live cross-site scripting exploit payloads intercepted.',
    business_impact: 'Perimeter block: Client-side exploit script intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Web Exploit Guardrail.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-vikram-04`,
    timestamp: new Date(now - 7200000).toISOString(),
    user: 'vikram.patel@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Command injection string').digest('hex'),
    original_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    sanitized_prompt: '[PAYLOAD_BLOCKED_BY_PERIMETER_GATEWAY]',
    risk_score: 96,
    risk_level: 'CRITICAL',
    attack_type: 'APPSEC_EXPLOIT',
    reasons: ['Detected OS command injection and reverse shell execution signature.'],
    action: 'BLOCK',
    rewritten_prompt: '',
    suggested_safe_prompt: 'Request blocked: OS command injection signature detected.',
    business_impact: 'Perimeter block: Command injection exploit intercepted.',
    alert_status: 'TRIGGERED',
    report_summary: 'Request blocked by security policy: Command Injection Guardrail.',
    provider_id: 'provider-safe-mock',
    latency_ms: 2,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-vikram-05`,
    timestamp: new Date(now - 1500000).toISOString(),
    user: 'vikram.patel@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Parameterized queries in Postgres').digest('hex'),
    original_prompt: 'How do parameterized queries in PostgreSQL prevent SQL injection attacks under the hood?',
    sanitized_prompt: 'How do parameterized queries in PostgreSQL prevent SQL injection attacks under the hood?',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'How do parameterized queries in PostgreSQL prevent SQL injection attacks under the hood?',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant application security query.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 22,
    has_file: false,
    override_status: 'NONE'
  },

  // =========================================================================
  // 6. SARAH JENKINS (People Operations & HR) - Fully Compliant
  // Blind Spot: None | Score: 100 (EXEMPLARY)
  // =========================================================================
  {
    id: `aegis-evt-sarah-01`,
    timestamp: new Date(now - 86400000).toISOString(),
    user: 'hr@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Interview assessment rubric').digest('hex'),
    original_prompt: 'Draft an interview assessment rubric for evaluating systems engineering candidates on collaborative problem solving.',
    sanitized_prompt: 'Draft an interview assessment rubric for evaluating systems engineering candidates on collaborative problem solving.',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Draft an interview assessment rubric for evaluating systems engineering candidates on collaborative problem solving.',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant HR operations draft.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 18,
    has_file: false,
    override_status: 'NONE'
  },
  {
    id: `aegis-evt-sarah-02`,
    timestamp: new Date(now - 3600000 * 4).toISOString(),
    user: 'hr@nexus-corp.com',
    user_role: 'USER',
    prompt_hash: crypto.createHash('sha256').update('Team building workshop ideas').digest('hex'),
    original_prompt: 'Suggest 4 constructive employee recognition practices for remote engineering teams.',
    sanitized_prompt: 'Suggest 4 constructive employee recognition practices for remote engineering teams.',
    risk_score: 0,
    risk_level: 'LOW',
    attack_type: 'None',
    reasons: [],
    action: 'ALLOW',
    rewritten_prompt: 'Suggest 4 constructive employee recognition practices for remote engineering teams.',
    suggested_safe_prompt: 'Prompt verified clean and approved for transmission.',
    business_impact: 'Safe compliant HR operations draft.',
    alert_status: 'NOT TRIGGERED',
    report_summary: 'Prompt verified clean and approved for transmission.',
    provider_id: 'provider-safe-mock',
    latency_ms: 19,
    has_file: false,
    override_status: 'NONE'
  }
];

// Deduplicate and merge into database
const existingIds = new Set(db.logs.map(l => l.id));
let addedCount = 0;
for (const log of newEmployeeLogs) {
  if (!existingIds.has(log.id)) {
    db.logs.unshift(log); // Add at beginning so they are recent
    addedCount++;
  }
}

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');
console.log(`Successfully seeded ${addedCount} employee logs and updated database.json.`);
